-- DROP & CREATE SEQUENCE, TABLE /  더미데이터
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
  cID      VARCHAR2(50) PRIMARY KEY,
  cPW      VARCHAR2(50) NOT NULL,
  cNAME    VARCHAR2(50) NOT NULL,
  cTEL     VARCHAR2(50),
  cEMAIL   VARCHAR2(50),
  cADDRESS VARCHAR2(50),
  cBIRTH   DATE,
  cGENDER  VARCHAR2(1)  CHECK(cGENDER='m' OR cGENDER='f'),
  cRDATE   DATE DEFAULT SYSDATE NOT NULL
);
SELECT * FROM CUSTOMER;