-- DROP & CREATE SEQUENCE, TABLE
DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;
DROP TABLE BOOK;
DROP SEQUENCE FILEBOARD_SEQ;
DROP SEQUENCE BOOK_SEQ;
CREATE TABLE BOOK(
  bID    NUMBER(7) PRIMARY KEY,
  bTITLE VARCHAR2(100) NOT NULL, -- 책이름
  bPRICE NUMBER(6)     NOT NULL, -- 책가격
  bIMAGE1 VARCHAR2(100) NOT NULL, -- 책 대표 이미지
  bIMAGE2 VARCHAR2(100) NOT NULL, -- 책 부가 이미지
  bCONTENT VARCHAR2(4000), -- 책설명(4000초과시 CLOB)
  bDISCOUNT NUMBER(3) NOT NULL,   -- 할인율
  bRDATE    DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
SELECT * FROM BOOK;
CREATE TABLE CUSTOMER (
  cID      VARCHAR2(50) PRIMARY KEY,
  cPW      VARCHAR2(50) NOT NULL,
  cNAME    VARCHAR2(50) NOT NULL,
  cTEL     VARCHAR2(50),
  cEMAIL   VARCHAR2(50),
  cADDRESS VARCHAR2(50),
  cBIRTH   DATE,
  cGENDER  VARCHAR2(1)  CHECK(cGENDER='m' OR cGENDER='f'),
  cRDATE   DATE DEFAULT SYSDATE NOT NULL
);
SELECT * FROM CUSTOMER;
CREATE TABLE FILEBOARD (
  FID NUMBER(6) PRIMARY KEY, -- 글번호
  CID VARCHAR2(50) REFERENCES CUSTOMER(CID) NOT NULL, -- 글쓴이 ID
  FTITLE VARCHAR2(100) NOT NULL, -- 글제목
  fCONTENT VARCHAR2(1000),       -- 글본문
  FILENAME VARCHAR2(100),        -- 첨부파일명
  FHIT     NUMBER(5) DEFAULT 0 NOT NULL,  -- 조회수
  FPW      VARCHAR2(50)   NOT NULL, -- 삭제용 비밀번호
  FGROUP   NUMBER(6)      NOT NULL,
  FSTEP    NUMBER(2)      NOT NULL,
  FINDENT  NUMBER(2)      NOT NULL,
  FIP      VARCHAR2(50)   NOT NULL,
  FRDATE   DATE       DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE FILEBOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT * FROM FILEBOARD;