-- [XII] 트랜젝션 명령어 ; COMMIT, ROLLBACK, SAVEPOINT
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
COMMIT;
------------------------------------------------
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=20;
DELETE FROM DEPT01 WHERE DEPTNO=30;
ROLLBACK;
------------------------------------------------
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=40;
COMMIT;
------------------------------------------------
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=30;
SELECT * FROM DEPT01;
SAVEPOINT C1;
DELETE FROM DEPT01 WHERE DEPTNO=20;
SELECT * FROM DEPT01;
SAVEPOINT C2;
DELETE FROM DEPT01 WHERE DEPTNO=10;
SELECT * FROM DEPT01;
ROLLBACK TO C1;
SELECT * FROM DEPT01;
COMMIT;
SELECT * FROM DEPT01;



