-- SQL활용
DROP TABLE MAJOR;
DROP TABLE STUDENT;
CREATE TABLE MAJOR (
 mCODE      NUMBER(1) PRIMARY KEY, 
 mNAME      VARCHAR2(30),
 mOFFICE    VARCHAR2(50)
);
 CREATE TABLE STUDENT (
  sNO        VARCHAR2(3) PRIMARY KEY,
  sNAME      VARCHAR2(50),
  sSCORE     NUMBER(3),
  mCODE      NUMBER(1) FOREIGN KEY,
);

INSERT INTO MAJOR (mCODE, mNAME, mOFFICE);
INSERT INTO MAJOR VALUES (101, '컴퓨터공학', 'A101호');
INSERT INTO MAJOR VALUES (102, '빅데이터', 'A102호');
INSERT INTO STUDENT (sNO, sNAME, sSCORE, mCODE)
 VALUES ('101', '홍길동', 99, 1);
INSERT INTO BOOK VALUES ('102', '신길동', 100, 2);

SELECT sNO, sNAME, sSCORE, mCODE, mNAME, mOFFICE
 FROM MAJOR M, STUDENT S
 WHERE M.mCODE = S.mCODE;
 